apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: node-cgroup-exporter
    release: dx-insight
  name: node-cgroup-exporter
  namespace: dx-insight
spec:
  endpoints:
  - interval: 30s
    port: http
    scheme: http
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: node-cgroup-exporter