apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    k8s-app: node-cgroup-exporter
  name: node-cgroup-exporter
  namespace: dx-insight
spec:
  clusterIP: None
  ports:
  - name: http
    port: 12927
    targetPort: 12927
  selector:
    app: node-cgroup-exporter